# version: "3.9"  # optional since v1.27.0
services:
  server-0:
    build: .
    ports:
      - "8080:8089"
    volumes:
      - ./local_data/server-0:/tmp/raft-data
      - ./local_configs/server-0:/config
    networks:
      - raft-net
  server-1:
    build: .
    ports:
      - "8081:8089"
    volumes:
      - ./local_data/server-1:/tmp/raft-data
      - ./local_configs/server-1:/config
    networks:
      - raft-net
  server-2:
    build: .
    ports:
      - "8082:8089"
    volumes:
      - ./local_data/server-2:/tmp/raft-data
      - ./local_configs/server-2:/config
    networks:
      - raft-net
  server-3:
    build: .
    ports:
      - "8083:8089"
    volumes:
      - ./local_data/server-3:/tmp/raft-data
      - ./local_configs/server-3:/config
    networks:
      - raft-net
  server-4:
    build: .
    ports:
      - "8084:8089"
    volumes:
      - ./local_data/server-4:/tmp/raft-data
      - ./local_configs/server-4:/config
    networks:
      - raft-net
networks:
  raft-net:
    driver: bridge