StateMachineType: sqlite
StateMachineConfig:
  SrcFileName: "/tmp/raft-data/statemc.db"

ServerDbType: sqlite
ServerDbConfig:
  SrcFileName: "/tmp/raft-data/server.db"

ServerId: server-0
Port: 8089

Peers:
  - HostName: server-0
    Address: server-0
  - HostName: server-1
    Address: server-1
  - HostName: server-2
    Address: server-2
  - HostName: server-3
    Address: server-3
  - HostName: server-4
    Address: server-4

RpcRetryLimit: 10
RpcTimeoutInSeconds: 86400

HeartBeatTickerIntervalInMilliseconds: 300 

MinFollowerTickerIntervalInMiliseconds: 600
MaxFollowerTickerIntervalInMiliseconds: 2000

MaxElectionTimeOutInSeconds: 100
ClientRequestTimeoutInSeconds: 30