StateMachineType: sqlite
StateMachineConfig:
  SrcFileName: "/tmp/raft-data/statemc.db"

ServerDbType: sqlite
ServerDbConfig:
  SrcFileName: "/tmp/raft-data/server.db"

ServerId: server-0
Port: 8089

Peers:
  - HostName: server-1
    Address: server-1
  - HostName: server-2
    Address: server-2
  - HostName: server-3
    Address: server-3
  - HostName: server-4
    Address: server-4
  - HostName: server-5
    Address: server-5

RpcRetryLimit: 1000
RpcTimeoutInSeconds: 86400
RpcRetryIntervalInMiliSeconds: 25

HeartBeatTickerIntervalInMilliseconds: 100 

MinFollowerTickerIntervalInMiliseconds: 500
MaxFollowerTickerIntervalInMiliseconds: 10000

InitialElectionTickerIntervalInMiliseconds: 20
ElectionTickerIntervalInMiliseconds: 1000

MaxElectionTimeOutInSeconds: 5
ClientRequestTimeoutInSeconds: 30