StateMachineType: sqlite
StateMachineConfig:
  SrcFileName: "/tmp/statemc.db"
ServerId: server1
ServerDbType: sqlite
ServerDbConfig:
  SrcFileName: "/tmp/server.db"
Peers: ['server2', 'server3', 'server4', 'server5']
TickerIntervalInMiliseconds: 150
RetryRPCLimit: 5
RPCTimeoutInSeconds: 10
ClientRequestTimeoutInSeconds: 30
ElectionTimerDurationInSeconds: 60